// build.rs — Auto-discover example scripts in `example_scripts/` and generate
// a Rust source file that embeds them at compile time.

use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    #[cfg(windows)]
    {
        let mut res = winres::WindowsResource::new();
        res.set_icon("assets/icon.ico");
        res.compile().unwrap();
    }

    let script_dir = Path::new("example_scripts");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("embedded_scripts.rs");

    // Tell Cargo to re-run this if the directory or any file in it changes
    println!("cargo:rerun-if-changed=example_scripts");

    let mut entries: Vec<_> = Vec::new();
    if script_dir.is_dir() {
        for entry in fs::read_dir(script_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) == Some("rhai") {
                let stem = path.file_stem().unwrap().to_string_lossy().to_string();
                let abs = fs::canonicalize(&path).unwrap();
                entries.push((stem, abs));
            }
        }
    }

    // Sort by filename so numbering (01_, 02_, …) determines order
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = fs::File::create(&dest).unwrap();

    writeln!(out, "/// Auto-generated by build.rs — do not edit.").unwrap();
    writeln!(out, "pub const BUILTIN_SCRIPTS: &[(&str, &str)] = &[").unwrap();

    for (stem, abs_path) in &entries {
        // Pretty name: strip leading "01_" prefix, replace underscores with spaces, title-case
        let display = pretty_name(stem);
        let path_str = abs_path.to_string_lossy();
        writeln!(
            out,
            "    (\"{}\", include_str!(r\"{}\")),",
            display, path_str
        )
        .unwrap();
    }

    writeln!(out, "];").unwrap();
}

/// Convert "02_quadratic_regression" → "Quadratic Regression"
fn pretty_name(stem: &str) -> String {
    // Strip leading digits and underscores (e.g. "01_", "02_")
    let stripped = stem.trim_start_matches(|c: char| c.is_ascii_digit() || c == '_');
    let stripped = if stripped.is_empty() { stem } else { stripped };

    stripped
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(c) => {
                    let upper: String = c.to_uppercase().collect();
                    format!("{}{}", upper, chars.as_str())
                }
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}
